import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen transition-all duration-300">
          {/* Sidebar */}
          <Sidebar />

          {/* Main Content Area */}
          <main className="flex-1 flex flex-col transition-all duration-300">
            {/* Header */}
            <div className="h-[70px] w-full bg-red-500 flex-shrink-0">
              <h1>hello</h1>
            </div>

            {/* Page Content */}
            <div className="bg-green-500 flex-1 overflow-auto p-4">
              <h1>huhu</h1>
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
